theme: jekyll-theme-minimal
title: Kiroong Choe
description: I always feel enthusiasm for so many things. Trying to suppress it to become professional, oftentimes it turns out I can't.
logo: https://user-images.githubusercontent.com/6987894/71638827-db64c480-2cad-11ea-83ba-2224f5ade63e.png
is_user_page: false
