theme: jekyll-theme-minimal
title: Kiroong Choe
description: I always feel enthusiasm for so many things. Trying to suppress it to become professional, oftentimes it turns out I can't.
logo: https://user-images.githubusercontent.com/6987894/71638808-4eba0680-2cad-11ea-90c6-4cc479f7e637.png
